### ISSUE TITLE
Rust: Write compressed files directly

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-wrap#20]
When converting datasets, it is sometimes feasible to buffer and write 1024^3 cubes of data. It would be great if we could write this data directly in a compressed file in order to save IO operations. 

@amotta What would be the challenges here?

**Comment by amotta** [comment]
Yes, this is a good idea - I've been thinking about this too.

This shouldn't be too difficult to implement. What's needed is a variant of [File::compress](https://github.com/scalableminds/webknossos-wrap/blob/7ad188ba5150fe5adbcc5f301a854700fb3275f8/rust/src/file.rs#L187..L212) that fills the block buffer `buf` by reading from a complete file buffer in Fortran order. This can be done with `Mat::copy_from`.
