### ISSUE TITLE
Python: Build PyPI package for Windows

### ISSUE THREAD

**Issue by amotta** [scalableminds/webknossos-wrap#26]
We're providing pre-built packages for macOS and Linux, but not for Windows. I consider this a rather significant omission.

Are there any big obstacles that keep us from building, testing, and publishing a Windows package via CircleCI, @normanrz?

**Comment by normanrz** [comment]
CircleCI doesn't support windows: https://support.circleci.com/hc/en-us/articles/115015871087-Windows-and-NET-Support
Travis does since recently. We could set it up there.

**Comment by amotta** [comment]
It seems that CircleCI now supports Windows. How difficult would it be to build and publish the Python `wkw` package for Windows?

**Comment by normanrz** [comment]
Seems like the plan that you need for Windows on CircleCI is crazy expensive. Github Actions will also support Windows builds. Perhaps that will be cheaper. I'll investigate what it takes to actually compile a Windows version, though. Need to find a Windows box first ;-)

**Comment by normanrz** [comment]
We have Windows builds now. Not automated yet. Will revisit when Github Actions are available.
